// File generated by FlutterFire CLI (configured for daily-work-tracker-e5831).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Whether Web Firebase configuration is provided.
  static bool get isWebConfigured =>
      web.apiKey.isNotEmpty && web.appId.isNotEmpty;

  /// Android FirebaseOptions extracted from android/app/google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxPK_3bWkrZJk7wffAqctaalfGaObrK8Q',
    appId: '1:823530124913:android:dcefecb5d1eb86a9778dd0',
    messagingSenderId: '823530124913',
    projectId: 'daily-work-tracker-e5831',
    storageBucket: 'daily-work-tracker-e5831.firebasestorage.app',
  );

  /// Web FirebaseOptions.
  /// To obtain these values for project "daily-work-tracker-e5831":
  /// 1. Open Firebase Console (https://console.firebase.google.com/) -> Project "daily-work-tracker-e5831".
  /// 2. Project Settings -> General -> "Your apps" section -> Click "Add app" (Web / </>)
  /// 3. Copy the apiKey and appId into the fields below.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '', // Web API key from Firebase Console
    appId: '',  // Web App ID from Firebase Console (e.g. 1:823530124913:web:...)
    messagingSenderId: '823530124913',
    projectId: 'daily-work-tracker-e5831',
    authDomain: 'daily-work-tracker-e5831.firebaseapp.com',
    storageBucket: 'daily-work-tracker-e5831.firebasestorage.app',
  );
}
